"""empty message

Revision ID: d28eda683a0b
Revises: 
Create Date: 2017-02-04 16:41:33.170514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28eda683a0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
